Feature/board
matrixpower1004/snowball-board pull request #16
Opened 2023-07-12 07:18 UTC by gosuuk

board Model 생성 확인 부탁드립니다. 수정사항이나 틀린 부분 있으면 말씀해 주시면 감사하겠습니다.

2023-07-12 07:25 UTC, jy-b commented
[PostHistory](https://github.com/matrixpower1004/snowball-board/blob/476d4c5df132fe31b4780723e769468e265791b2/src/main/java/com/snowball/board/domain/board/model/PostsHistory.java)
[Posts](https://github.com/matrixpower1004/snowball-board/blob/476d4c5df132fe31b4780723e769468e265791b2/src/main/java/com/snowball/board/domain/board/model/Posts.java)
userRole은 Enum Type이여야 하지 않을까요

2023-07-12 07:44 UTC, jy-b commented
Setter를 사용해야 하는 상황이 없으면 안붙여도 될거 같습니다

2023-07-12 08:07 UTC, matrixpower1004 commented on src/main/java/com/snowball/board/domain/board/model/PostsHistory.java
> +}
satateCode enum으로 안 만들고 String 으로 그냥 넣을실건가요?

2023-07-12 08:31 UTC, gosuuk commented on src/main/java/com/snowball/board/domain/board/model/PostsHistory.java
> +}
수정했습니다. 확인 못해서 죄송합니다.

2023-07-12 20:48 UTC, matrixpower1004 commented on src/main/java/com/snowball/board/common/util/StateType.java
> +    DISSOLUTION("해체");
해체? 해제 아닌가요? 오타 수정해 주세요.

2023-07-13 00:52 UTC, matrixpower1004 requested changes
리뷰 내용 참고하셔서 다시 pr 해주세요.

2023-07-13 03:56 UTC, matrixpower1004 approved these changes
👍

2023-07-13 03:57 UTC, merged

2023-07-13 04:04 UTC, Coding9nt commented on src/main/java/com/snowball/board/common/util/StateType.java
> +    DISSOLUTION("해체");
SHOW 가 더 괜찮을 것같습니다.